### PR TITLE
✨Add Visitor Counter feature done ! #59

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #59
Add Visitor Counter feature done properly -

Screenshot 2024-10-24 191217

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 PA merge my PR with level 3 & gssoc-ext tag, If you check other projects, they are also giving level 3 for this..

Screenshot 2024-10-22 204511

You can check my code also...

Thank you 🙏🏻

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 done, merge my PR with level 3 & gssoc-ext tag, If you check other projects, they are also giving level 3 for this..
> 
> Screenshot 2024-10-22 204511
> 
> You can check my code also...
> 
> Thank you 🙏🏻

@Akshat111111 please merge my PR, otherwise I can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 please merge my PR, otherwise I can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 please merge my PR, otherwise I can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 please merge my PR, otherwise I can't able to do another task..

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 ?? today is the last day please merge my PR with level 3 ..

**Review by Akshat111111 — APPROVED** [review]
Nice implemented

**Comment by Subhajit-2023-44** [comment]
> Nice implemented

@Akshat111111 sir please add level 3, i add this new feature,  If you check other projects, they are also giving level 3 for this..

**Pull request merged**
