### PR TITLE
Added Copyright at footer and Terms of Service page

### LINKED ISSUE #82: Adding a copyright and terms of services at footer of page
Adding a footer that displays the **copyright** information alongside a "**Terms of Service**" link. The link should navigate to a new page when clicked, providing users with access to important legal terms and conditions.
 
**Ex:** © 2024 NexTrade. All rights reserved. | Terms of Service

@Akshat111111  please kindly assign this issue under gssoc-extd, hacktoberfest-accepted and level2

### PR DESCRIPTION
**Pull request by siri-chandana-macha**
closes #82 
I have added a copy right at footer and when clicked on terms of services it navigates to terms of service page

**Note:** Please add level2  , gssoc-extd and hacktoberfest-accepted.
Screenshot 2024-11-01 224635
image

### CODE REVIEW

**Comment by siri-chandana-macha** [comment]
@Akshat111111 
**".github/workflows/greetings.yml / welcome (pull_request_target) Failing after 3s"**
This is failing because you didn't enable **read and write permissions** in your repo settings follow the steps in #58 
I have shared you screenshots. regarding automessages on issues and pr's.

**Review by Akshat111111 — CHANGES_REQUESTED** [review]
remove the conflict

**Comment by siri-chandana-macha** [comment]
Yeah I will change

**Comment by siri-chandana-macha** [comment]
I have resolved the conflicts and I am 
submitting one pull request for **both** adding social media icons #69  and Copyright, Terms of Service #82 
please add **level2** for this 
and also **add gssoc-extd, hacktoberfest-accepted**

**Review by Akshat111111 — APPROVED** [review]
fine!

**Pull request merged**
