### PR TITLE
Add a User Profiles page done ! #85

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #85
Add a normal user profile page and a profile icon in the home page that redirects to the profile page done -

Profile page -
Screenshot 2024-11-02 225028
Screenshot 2024-11-02 225035

Home page -
Screenshot 2024-11-02 225056

https://github.com/user-attachments/assets/b5e48754-70ad-43dd-8f62-a2affbc173a5

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir done, please merge my PR with level 3 & gssoc-ext label, 

you can check my code i have added a lot..

Thank You 🙏🏻

**Review by Akshat111111 — COMMENTED** [review]
Great work, But remove the conflicts first so that I can merge

**Comment by Subhajit-2023-44** [comment]
> Great work, But remove the conflicts first so that I can merge

@Akshat111111 sir done

**Review by Akshat111111 — APPROVED** [review]
Perfect !

**Comment by Subhajit-2023-44** [comment]
> Perfect !

Thank you sir 🙏🏻, sir please add level 3 and gssoc-ext label, you can check my code i have added a lot..

**Comment by Subhajit-2023-44** [comment]
> Perfect !

@Akshat111111 Thank you sir 🙏🏻, sir please add level 3 and gssoc-ext label, you can check my code i have added a lot..

**Comment by Subhajit-2023-44** [comment]
> Perfect !

@Akshat111111 Thank you sir 🙏🏻, sir please add level 3 and gssoc-ext label, you can check my code i have added a lot..

**Pull request merged**
