### PR TITLE
Add Signup/Register page done ! #117 🟢🟢

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add Signup/Register page done - #117

https://github.com/user-attachments/assets/a48eb30f-1c31-4dc3-9380-60725ac115d2

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please merge my PR with Level 3 and gssoc-ext label, you can check my code and video i added a lot..


Thank You

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please merge my PR with Level 3 and gssoc-ext label, you can check my code and video i added a lot..

Thank You

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Review by Akshat111111 — APPROVED** [review]
It works

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please add level 3, i added a lot

image

**Pull request merged**
