### PR TITLE
chatbot added✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
@Akshat111111 i have added the chatbot , please review this.

https://github.com/user-attachments/assets/7aa4bd4d-454d-41b2-af86-60583dbc68b0

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have 1more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have 1more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have 1more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have 1more PR to make.

**Review by Akshat111111 — APPROVED** [review]
Yeah, it works !

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you assign the level aswell , thank you!

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 btw , is gssoc tag there aswell? becasue im participating for that. sorry to disturb

**Pull request merged**
