### PR TITLE
Update Readme.md added Fundamentals of Blockchain and Ethereum

### PR DESCRIPTION
**Pull request by shivenyadavs**
Added Transaction Lifecycle Sections: Organized the content into sections detailing the steps of a blockchain transaction lifecycle, including:

Initiation of a transaction
Transaction propagation
Mining and confirmation
Transaction settlement
Included Post-Transaction Activities: Listed activities that occur after a transaction is confirmed, such as verification, monitoring, and dispute resolution.

Outlined Challenges: Highlighted potential challenges faced during the transaction lifecycle, including network congestion, limited throughput, and security concerns.

### CODE REVIEW

**Comment by shivenyadavs** [comment]
@Akshat111111 can you please check the changes made.

**Review by Akshat111111 — COMMENTED** [review]
I think I have merged this PR ???

**Comment by shivenyadavs** [comment]
ok

**Comment by shivenyadavs** [comment]
but nothing seems to be new in the readme.md file can you please check and then merge it

**Comment by shivenyadavs** [comment]
please check my content and then compare it

**Comment by shivenyadavs** [comment]
if u want to close this u can close it

**Comment by shivenyadavs** [comment]
@Akshat111111 can you please respond it is very difficult to understand

**Review by Akshat111111 — COMMENTED** [review]
Please make a new PR with only the functionality thats not added yet

**Comment by shivenyadavs** [comment]
i have added a detailed information and pdf which explains the working of ethereum please look into this.

**Comment by shivenyadavs** [comment]
Uploading Screen Recording 2024-11-02 225935.mp4…

please see this.

**Comment by shivenyadavs** [comment]
please look into this and merge it

**Review by Akshat111111 — APPROVED** [review]
Fine

**Pull request merged**
