### PR TITLE
Add/Enable PWA (Progressive Web App) done !  #101 🟢🌟

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add/Enable PWA (Progressive Web App) done !  #101 

🟢Key Features of PWAs:

🔵Offline Capability: Using service workers, PWAs can function offline or in low-network conditions by caching essential assets.
🔵App-like Experience: PWAs behave like native apps, with smooth animations, navigation, and interactions, even on mobile.
🔵Push Notifications: PWAs can send push notifications to engage users, even when the app is not open.
🔵Installability: PWAs can be installed on the user’s home screen, just like a native app, without going through app stores.
🔵Fast Loading: By caching resources and using service workers, PWAs can load quickly, even with slow network conditions.
🔵Responsive: They adapt to any device, whether it's a mobile, tablet, or desktop.

https://github.com/user-attachments/assets/0b99a36d-7c77-4b17-81aa-ea4485789b8d

Screenshot 2024-11-08 165101

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir done, please merge my PR 

image

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 sir done, please merge my PR
> 
> image

@Akshat111111 sir

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 sir done, please merge my PR
> 
> image

@Akshat111111

**Review by Akshat111111 — COMMENTED** [review]
kindly resolve the conflicts

**Comment by Subhajit-2023-44** [comment]
> kindly resolve the conflicts

@Akshat111111 sir done

**Pull request merged**
