### PR TITLE
Add Footer done ! #103

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add Footer done - #103

Screenshot 2024-11-08 180855

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir done, please merge my PR

image

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 sir done, please merge my PR
> 
> image

@Akshat111111

**Review by Akshat111111 — APPROVED** [review]
fine

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please merge all PR's and add label 

sir today is the last day

**Pull request merged**
