### PR TITLE
multi language support added 

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
this is working, issue #33 solved.
@Akshat111111 can you review this please .

https://github.com/user-attachments/assets/1583fff0-9e46-4dae-a157-69504d75eb5b

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have one more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have one more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have one more PR to make.

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 can you please review this , i have one more PR to make.

**Review by Akshat111111 — COMMENTED** [review]
The feature is well implemented, But remove the conflicts so that I can merge

**Comment by T-Rahul-prabhu-38** [comment]
@Akshat111111 i have fixed the conflicts , please review this .
thank you

**Review by Akshat111111 — APPROVED** [review]
Now its perfect !

**Pull request merged**
