### PR TITLE
Add Edit Profile Feature in Profile Page done ! #99 🟢

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add Edit Profile Feature in Profile Page done - #99 

https://github.com/user-attachments/assets/58516f58-3f91-461f-85dd-5714f09f83c9

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 done, sir please merge my PR and add Level 3 & gssoc-ext label

sir you can check my code, i added a lot & sir if you check other projects they also give level 3 for this..

Screenshot 2024-11-08 184830


Screenshot 2024-11-08 184922

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 done, sir please merge my PR and add Level 3 & gssoc-ext label
> 
> sir you can check my code, i added a lot & sir if you check other projects they also give level 3 for this..
> 
> Screenshot 2024-11-08 184830
> 
> Screenshot 2024-11-08 184922

@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Review by Akshat111111 — APPROVED** [review]
Good work !

**Comment by Subhajit-2023-44** [comment]
> Good work !

@Akshat111111 Thank you sir please merge all PR's

**Pull request merged**
