### PR TITLE
Add a pop up dialog box for subscribing to newsletter done ! #105

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Add a pop up dialog box for subscribing to newsletter done - #105

Screenshot 2024-11-08 182803
Screenshot 2024-11-08 182814

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir kindly merge my PR with Level 3 and gssoc-ext label, If you check other projects, they are also giving level 3 for this.. i add this new feature, You can check my code also...

Screenshot 2024-10-28 204225
Screenshot 2024-10-28 204307


Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
> @Akshat111111 sir kindly merge my PR with Level 3 and gssoc-ext label, If you check other projects, they are also giving level 3 for this.. i add this new feature, You can check my code also...
> 
> Screenshot 2024-10-28 204225 Screenshot 2024-10-28 204307
> 
> Thank You 🙏🏻

@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Review by Akshat111111 — APPROVED** [review]
Fine !!

**Comment by Subhajit-2023-44** [comment]
Thanks a lot sir 🙏🏻🙏🏻

**Pull request merged**
