### PR TITLE
Updated Scroll Button Functionality 

### PR DESCRIPTION
**Pull request by ak-0283**
I have made the following updates to your project:

**1. Scroll Button Enhancement:**
   - Modified the scroll button functionality to trigger at 10px instead of 300px for improved usability and a smoother experience for users scrolling shorter distances.

**2. Missing `style` Tag Fix:**
   - Discovered that the `style` tag was missing from the webpage, causing certain styles not to be applied correctly. I have added the necessary `style` tag and ensured the styles are properly embedded.

These changes aim to enhance both functionality and aesthetics, ensuring a smoother user experience and fixing the styling issues.

Please review the changes and let me know if any further adjustments are required!

**How to Test:**
- Scroll down on the page to 10px and verify that the scroll button appears.
- Check that the updated styles are now applied correctly after the `style` tag addition.

**Before:**

IMg1

**After:**

IMG2

IMG3

**Please Review and Merge it** @Akshat111111 #54

### CODE REVIEW

**Review by Akshat111111 — COMMENTED** [review]
kindly resolve conflict and make new pr

**Comment by ak-0283** [comment]
i have resolve the issue please review and merge it @Akshat111111

**Comment by ak-0283** [comment]
or else i have to make new pr @Akshat111111

**Review by Akshat111111 — APPROVED** [review]
fine!

**Pull request merged**
