### PR TITLE
Add a new page to display all contributors done ! #61 ✨

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new Contributors page - #61

Add Contributors page done - It display all Contributors

Screenshot 2024-10-30 050513

Page link in footer..

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 done, please merge my PR with level 3,

you can check my code...

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please merge my PR with level 3,

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Review by Akshat111111 — COMMENTED** [review]
work is good, but resolve the conflict

**Comment by Subhajit-2023-44** [comment]
> work is good, but resolve the conflict
@Akshat111111 done 

image

**Comment by Subhajit-2023-44** [comment]
@Akshat111111 sir please merge my PR with level 3... If you check other projects they also give level 3 for this.. you can check my code..

Thank You

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Comment by Subhajit-2023-44** [comment]
@Akshat111111

**Review by Akshat111111 — COMMENTED** [review]
fine!!

**Pull request merged**
